### ISSUE TITLE
purescript-halogen-svg not maintained

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [JordanMartinez/learn-halogen#30]
In It does not appear that purescript-halogen-svg will be upgraded for halogen 5. https://github.com/kwohlfahrt/purescript-halogen-svg/issues/7

From lesson [src/01-Static-HTML/01-Static-HTML.md](https://github.com/JordanMartinez/learn-halogen/blob/latestRelease/src/01-Static-HTML/01-Static-HTML.md)

**Comment by JordanMartinez** [comment]
How should we proceed from here?

Should I tack on a "(unmaintained)" note at the end of that entry?

**Comment by BebeSparkelSparkel** [comment]
https://github.com/rnons seems to have some halogen svg repos. Would any of those work?

**Comment by JordanMartinez** [comment]
You could, but it would come at the cost of losing type safety. So, you'd have no way of knowing whether there was an issue in your SVG string until runtime.

**Comment by JordanMartinez** [comment]
I'll close this issue due to inactivity and because the real issue is that the library in question here needs to be updated.
