### ISSUE TITLE
Generate Docs with spago-docs-search

### ISSUE THREAD

**Issue by zhujinxuan** [JordanMartinez/learn-halogen#31]
Hi, thank you for this nice project.

In reading the projects, it always include some looking up definitions through `./generated-docs/index.html`.  https://github.com/spacchetti/purescript-docs-search provides a nice search box to easy the search process.

Perhaps it is nice to add the docs-search in the project.

**Comment by JordanMartinez** [comment]
Thanks! I like that idea. I knew the author had recently claimed to have created something like this, but I wasn't aware of this project.

**Comment by JordanMartinez** [comment]
To resolve this issue, we would need to
- Add a step to install that package [in the Requirements part of this project's ReadMe](https://github.com/JordanMartinez/learn-halogen#requirements)
- Add a step to run that command [in the Instructions part of this project's ReadMe](https://github.com/JordanMartinez/learn-halogen#instructions)
- Update the `.travis.yml` file to install that project and run its command to verify it still works over time.

**Comment by klntsky** [comment]
Very likely you don't need to do anything, cause the `purescript-docs-search` project will soon be integrated into spago, and you already recommend installing spago at the requirements section of the README.

**Comment by JordanMartinez** [comment]
Great! Looking forward to it!

**Comment by klntsky** [comment]
Yep, [it happened](https://github.com/spacchetti/spago/releases/tag/0.9.0.0).

**Comment by zhujinxuan** [comment]
Great, thank you @klntsky .  I think I can close this issue now.
