### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by srghma** [JordanMartinez/learn-halogen#36]
1) this guide is hard to read because I always have to check the exact definition of functions in `src/Scaffolding` folder, Ideally I would like this folder to be deleted and util functions should not be used. Each example should be self-sufficient. If you dont want to tell about something beforehand - you can just write "More about this field later."

~2) I would be good to have the results of compilation to be included in project, near the examples~

**Comment by JordanMartinez** [comment]
> If you dont want to tell about something beforehand - you can just write "More about this field later."

[In the last paragraph of this section](https://github.com/JordanMartinez/learn-halogen/tree/latestRelease/src#learn-halogen), I state:
> To limit this feeling of being overwhelmed, we'll provide some scaffolding that "hides" irrelevant things from you until you understand the foundational concepts first. This scaffolding code will be stored in the `Scaffolding` folder. Feel free to ignore this folder until after you have finished reading through the rest of the folder's contents.

Doesn't that address what you're bringing up here?

**Comment by srghma** [comment]
No, I mean I don't think this hiding is good, it makes everything even harder to learn, instead of learning only api of halogen I need to learn the scaffolding api also and keep that api in my head while I'm looking at examples

That's just how I feel

**Comment by JordanMartinez** [comment]
That makes sense.

So, you're proposal is to change a given lesson's file to a structure like below?
```purescript
module Some.Module where

-- Imports necessary for scaffolding that we don't want to focus on
import Halogen
-- ...
---------------------------------------------------

-- Imports necessary to what we're doing in a specific lesson
import Halogen.HTML

-- actual lesson here


-------------------------------------------------------------
-- all scaffolding code here
```

**Comment by srghma** [comment]
well, not exactly, I thought about not using util functions at all

but I dont know if this is good idea

for first chapter it makes sense to use util functions, because reader can see more types 

but it becomes harder to read starting from second chapter

I dont know, just wanted to share feelings
