### ISSUE TITLE
`--no-minify` is not supported by `serve` action of `parcel`

### ISSUE THREAD

**Issue by vlatkoB** [JordanMartinez/learn-halogen#46]
In the [Learn Halogen](https://github.com/JordanMartinez/learn-halogen/blob/v2.3.0/src/ReadMe.md) there is a compilation instruction:
```parcel serve assets/path/to/corresponding/HTML_File.html -o HTML_File--parcelified.html --open --no-minify```
However, `parcel serve` does not support `--no-minify`, only `parcel build` suports it.

**Comment by JordanMartinez** [comment]
I've fixed that in 9f3fcbd3018237a07040d2a021c92dcefb4491ca

It'll be included in next release.

**Comment by JordanMartinez** [comment]
Also, in this situation, these instructions are illustrative. The real ones are found in later files.

**Comment by vlatkoB** [comment]
This is (still) my first read and when I got to that first page, I immediately wanted to try the first example. That is how I stumbled upon this issue.

**Comment by JordanMartinez** [comment]
Ahh, that makes sense.

Even so, I'm glad you brought the issue up.
