### ISSUE TITLE
launchAff_ vs runHalogenAff

### ISSUE THREAD

**Issue by milesfrain** [JordanMartinez/learn-halogen#64]
I noticed the [official halogen examples](https://github.com/purescript-halogen/purescript-halogen/blob/master/examples/basic/src/Main.purs) use [`runHalogenAff`](https://pursuit.purescript.org/search?q=runhalogenaff), while your examples use [`launchAff_`](https://pursuit.purescript.org/search?q=launchaff_).
Both seem to behave identically, but perhaps that's only in situations where no exceptions are thrown.
How do you feel about converting your examples to be more consistent with the other learning materials out there?
Should there be a note added describing the differences and situations where one would be preferred over the other?

**Comment by JordanMartinez** [comment]
It makes sense to convert it to runHalogenAff. And yes, there should be a
note about why that's used rather than launchAff_

**Comment by JordanMartinez** [comment]
I'm fixing this in upcoming release as well.
