### ISSUE TITLE
Recommend spago's --watch feature in automatic reload instructions

### ISSUE THREAD

**Issue by jhrcek** [JordanMartinez/learn-halogen#71]
In https://github.com/JordanMartinez/learn-halogen/blob/latestRelease/src/01-Static-HTML/01-Static-HTML.md#automatic-reload there's a recommendation of using watchexec tool for automatic rebuilding of  purs source files. Instead of introducing another external tool, it might be better to recommend spago's `--watch` feature which achieves the same without requiring external tool. I can make a PR if you agree with my proposal.

**Comment by JordanMartinez** [comment]
@milesfrain Since you added #63, do you care to comment on this?

**Comment by JordanMartinez** [comment]
@jhrcek If we don't here from `milesfrain` in 3 days, then go for it. AFAICT, they do the same thing but the `watchexec` install is not necessary. I think I thought `watchexec` did more than just recompile the code (e.g. reload the page, too).

**Comment by jhrcek** [comment]
When you have `parcel serve ...` running in one terminal window and run `spago build --watch ...` in another terminal it reloads the code live in the browser after saving the .purs file in the editor, so to me it feels functionally equivalent to using watchexec.

**Comment by JordanMartinez** [comment]
Functionally equivalent, yes, but the extra terminal window may put off others, too. I think I found that part annoying myself. That could be fixed if there was Spago-integration for Parcel.

**Comment by milesfrain** [comment]
@jhrcek I agree with your proposal.

I added this note after reading https://github.com/purescript/spago/issues/65, but somehow missed that the `--watch` flag also works with `bundle-app`.

A small annoyance with either of these workflows is that there's a fairly noticeable delay between file save and page reload (at least on my slower machine). It may be nice to encourage some other faster options, such as psc-ide + parcel (demonstrated [here](https://github.com/purescript-templates/halogen)). Another possibility is to configure this learning repo with [purescript-halogen-storybook](https://github.com/rnons/purescript-halogen-storybook), so users can jump to the next example without running another rebuild command.

**Comment by JordanMartinez** [comment]
Ok, @jhrcek would you mind submitting a PR that removes `watchexec` and uses `spago` with the `-w` flag instead?

> Another possibility is to configure this learning repo with purescript-halogen-storybook, so users can jump to the next example without running another rebuild command.

I like this idea. Let's track this in another issue.
