### ISSUE TITLE
Change `purescript-jordans-reference` links to use its `latestRelease` branch?

### ISSUE THREAD

**Issue by FranklinChen** [JordanMartinez/learn-halogen#75]
The `ReadMe.md` has links to your reference site such as https://github.com/JordanMartinez/purescript-jordans-reference/tree/ps-0.13.x-v0.17.1/11-Syntax/01-Basic-Syntax but maybe should be linked to the `latestRelease` branch instead of `ps-0.13.x-v0.17.1`? I noticed the discrepancy when see comments about issues that have since been resolved in `latestRelease`.

**Comment by JordanMartinez** [comment]
Ah... yeah. So, I did it that way because then those links would always work. If I link to `latestRelease`, the headers / file names might change. Unfortunately, that means these links go stale. It might be better to just link to the ReadMe of my learning repo and then direct the user where to go from there.

Thoughts?

**Comment by FranklinChen** [comment]
Perhaps you are right, and it would suffice to just link to the learning repo. I assume most people who wish to learn about Halogen already have a fair amount of familiarity with PureScript and can pick and choose what they wish to review if they need to.

**Comment by JordanMartinez** [comment]
On the other hand, that link refers to a folder whose name hasn't changed throughout the entire history of the repo. So, I think it'll be fine in this case.

**Comment by FranklinChen** [comment]
It's not just this link, though, but all the others as well. A couple of them have been renamed in the `latestRelease` branch, however.

**Comment by JordanMartinez** [comment]
Ok, let's swap them over to `latestRelease` then. It'll probably be better to take the approach of "fix this broken link" rather than "this link is old." The former is more obvious than the latter and will likely produce more issues that we can fix sooner.

Mind submitting such a PR?

**Comment by FranklinChen** [comment]
Will do.
